version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node
      - python

  php:
    build: ./php
    volumes:
      - ./php/app:/var/www/html
    expose:
      - "9000"

  nginx-php:
    image: nginx:latest
    ports:
      - "8002:80"
    volumes:
      - ./php/app/public:/var/www/html
      - ./nginx/php.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php


  node:
    build: ./node
    volumes:
      - ./node/app:/usr/src/app
    ports:
      - "3000:3000"

  python:
    build: ./python
    volumes:
      - ./python/app:/usr/src/app
    ports:
      - "8001:8001"
